### ISSUE TITLE
ToyDragon / CharacterRandomizer

### ISSUE THREAD

**Issue by harbingerofme** [IFixYourRoR2Mods/Mod-Request#1]
**I have checked the wontfix.md to see if this mod is on there:**
`yes`

**The link to the mod on thunderStore is:**
https://thunderstore.io/package/ToyDragon/CharacterRandomizer/

**This mod is open source:**
`yes`

**If applicable, repo link**
https://github.com/ToyDragon/ROR2ModCharacterRandomizer/blob/master/CharacterRandomizerOverhaul.cs

**Expected effort:**
`update broken code`

Discord UserId that requested it: `203979311882043392`

**Comment by IFixYourRoR2Mods** [comment]
Fixed by b20a1fe76b0c2b7ab5fdb3de3499bd772b8c6462
