### ISSUE TITLE
WhelanB's Discord RPC

### ISSUE THREAD

**Issue by LONGACAT** [IFixYourRoR2Mods/Mod-Request#3]
https://thunderstore.io/package/WhelanB/DiscordRichPresence/
https://github.com/WhelanB/RoR2-Discord-RP

Causes scenes not to load when starting a game.

**Comment by IFixYourRoR2Mods** [comment]
https://github.com/IFixYourRoR2Mods/RoR2-Discord-RP/releases/tag/CU3
It's done.
